package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Integer idCalificacion;
     private InfoVideo infoVideo;
     private String calificacion;

    public Calificacion() {
    }

    public Calificacion(InfoVideo infoVideo, String calificacion) {
       this.infoVideo = infoVideo;
       this.calificacion = calificacion;
    }
   
    public Integer getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public InfoVideo getInfoVideo() {
        return this.infoVideo;
    }
    
    public void setInfoVideo(InfoVideo infoVideo) {
        this.infoVideo = infoVideo;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }




}


