package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrito generated by hbm2java
 */
public class Carrito  implements java.io.Serializable {


     private Integer idCarrito;
     private Usuario usuario;
     private String precioTotal;
     private String fecha;
     private String estado;
     private Set<CarritoHasInfoVideo> carritoHasInfoVideos = new HashSet<CarritoHasInfoVideo>(0);

    public Carrito() {
    }

	
    public Carrito(Usuario usuario, String precioTotal, String fecha, String estado) {
        this.usuario = usuario;
        this.precioTotal = precioTotal;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Carrito(Usuario usuario, String precioTotal, String fecha, String estado, Set<CarritoHasInfoVideo> carritoHasInfoVideos) {
       this.usuario = usuario;
       this.precioTotal = precioTotal;
       this.fecha = fecha;
       this.estado = estado;
       this.carritoHasInfoVideos = carritoHasInfoVideos;
    }
   
    public Integer getIdCarrito() {
        return this.idCarrito;
    }
    
    public void setIdCarrito(Integer idCarrito) {
        this.idCarrito = idCarrito;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(String precioTotal) {
        this.precioTotal = precioTotal;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<CarritoHasInfoVideo> getCarritoHasInfoVideos() {
        return this.carritoHasInfoVideos;
    }
    
    public void setCarritoHasInfoVideos(Set<CarritoHasInfoVideo> carritoHasInfoVideos) {
        this.carritoHasInfoVideos = carritoHasInfoVideos;
    }




}


