package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clasificacion generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer idClasificacion;
     private String clasificacion;
     private Set<InfoVideo> infoVideos = new HashSet<InfoVideo>(0);

    public Clasificacion() {
    }

	
    public Clasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Clasificacion(String clasificacion, Set<InfoVideo> infoVideos) {
       this.clasificacion = clasificacion;
       this.infoVideos = infoVideos;
    }
   
    public Integer getIdClasificacion() {
        return this.idClasificacion;
    }
    
    public void setIdClasificacion(Integer idClasificacion) {
        this.idClasificacion = idClasificacion;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Set<InfoVideo> getInfoVideos() {
        return this.infoVideos;
    }
    
    public void setInfoVideos(Set<InfoVideo> infoVideos) {
        this.infoVideos = infoVideos;
    }




}


