package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String genero;
     private Set<GeneroHasInfoVideo> generoHasInfoVideos = new HashSet<GeneroHasInfoVideo>(0);

    public Genero() {
    }

	
    public Genero(String genero) {
        this.genero = genero;
    }
    public Genero(String genero, Set<GeneroHasInfoVideo> generoHasInfoVideos) {
       this.genero = genero;
       this.generoHasInfoVideos = generoHasInfoVideos;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Set<GeneroHasInfoVideo> getGeneroHasInfoVideos() {
        return this.generoHasInfoVideos;
    }
    
    public void setGeneroHasInfoVideos(Set<GeneroHasInfoVideo> generoHasInfoVideos) {
        this.generoHasInfoVideos = generoHasInfoVideos;
    }




}


