package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InfoVideo generated by hbm2java
 */
public class InfoVideo  implements java.io.Serializable {


     private Integer idInfoVideo;
     private Clasificacion clasificacion;
     private TipoVideo tipoVideo;
     private String nombreVideo;
     private String imagen;
     private String precio;
     private String personajePrincipal;
     private Set<Calificacion> calificacions = new HashSet<Calificacion>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<CarritoHasInfoVideo> carritoHasInfoVideos = new HashSet<CarritoHasInfoVideo>(0);
     private Set<Video> videos = new HashSet<Video>(0);
     private Set<GeneroHasInfoVideo> generoHasInfoVideos = new HashSet<GeneroHasInfoVideo>(0);

    public InfoVideo() {
    }

	
    public InfoVideo(Clasificacion clasificacion, TipoVideo tipoVideo, String nombreVideo, String imagen, String precio) {
        this.clasificacion = clasificacion;
        this.tipoVideo = tipoVideo;
        this.nombreVideo = nombreVideo;
        this.imagen = imagen;
        this.precio = precio;
    }
    public InfoVideo(Clasificacion clasificacion, TipoVideo tipoVideo, String nombreVideo, String imagen, String precio, String personajePrincipal, Set<Calificacion> calificacions, Set<Persona> personas, Set<CarritoHasInfoVideo> carritoHasInfoVideos, Set<Video> videos, Set<GeneroHasInfoVideo> generoHasInfoVideos) {
       this.clasificacion = clasificacion;
       this.tipoVideo = tipoVideo;
       this.nombreVideo = nombreVideo;
       this.imagen = imagen;
       this.precio = precio;
       this.personajePrincipal = personajePrincipal;
       this.calificacions = calificacions;
       this.personas = personas;
       this.carritoHasInfoVideos = carritoHasInfoVideos;
       this.videos = videos;
       this.generoHasInfoVideos = generoHasInfoVideos;
    }
   
    public Integer getIdInfoVideo() {
        return this.idInfoVideo;
    }
    
    public void setIdInfoVideo(Integer idInfoVideo) {
        this.idInfoVideo = idInfoVideo;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public TipoVideo getTipoVideo() {
        return this.tipoVideo;
    }
    
    public void setTipoVideo(TipoVideo tipoVideo) {
        this.tipoVideo = tipoVideo;
    }
    public String getNombreVideo() {
        return this.nombreVideo;
    }
    
    public void setNombreVideo(String nombreVideo) {
        this.nombreVideo = nombreVideo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getPersonajePrincipal() {
        return this.personajePrincipal;
    }
    
    public void setPersonajePrincipal(String personajePrincipal) {
        this.personajePrincipal = personajePrincipal;
    }
    public Set<Calificacion> getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set<Calificacion> calificacions) {
        this.calificacions = calificacions;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<CarritoHasInfoVideo> getCarritoHasInfoVideos() {
        return this.carritoHasInfoVideos;
    }
    
    public void setCarritoHasInfoVideos(Set<CarritoHasInfoVideo> carritoHasInfoVideos) {
        this.carritoHasInfoVideos = carritoHasInfoVideos;
    }
    public Set<Video> getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set<Video> videos) {
        this.videos = videos;
    }
    public Set<GeneroHasInfoVideo> getGeneroHasInfoVideos() {
        return this.generoHasInfoVideos;
    }
    
    public void setGeneroHasInfoVideos(Set<GeneroHasInfoVideo> generoHasInfoVideos) {
        this.generoHasInfoVideos = generoHasInfoVideos;
    }




}


