package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Isan generated by hbm2java
 */
public class Isan  implements java.io.Serializable {


     private Integer idIsan;
     private String isan;
     private Set<Video> videos = new HashSet<Video>(0);

    public Isan() {
    }

	
    public Isan(String isan) {
        this.isan = isan;
    }
    public Isan(String isan, Set<Video> videos) {
       this.isan = isan;
       this.videos = videos;
    }
   
    public Integer getIdIsan() {
        return this.idIsan;
    }
    
    public void setIdIsan(Integer idIsan) {
        this.idIsan = idIsan;
    }
    public String getIsan() {
        return this.isan;
    }
    
    public void setIsan(String isan) {
        this.isan = isan;
    }
    public Set<Video> getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set<Video> videos) {
        this.videos = videos;
    }




}


