package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lenguaje generated by hbm2java
 */
public class Lenguaje  implements java.io.Serializable {


     private Integer idLenguaje;
     private String lenguaje;
     private Set<VideoHasLenguaje> videoHasLenguajes = new HashSet<VideoHasLenguaje>(0);

    public Lenguaje() {
    }

	
    public Lenguaje(String lenguaje) {
        this.lenguaje = lenguaje;
    }
    public Lenguaje(String lenguaje, Set<VideoHasLenguaje> videoHasLenguajes) {
       this.lenguaje = lenguaje;
       this.videoHasLenguajes = videoHasLenguajes;
    }
   
    public Integer getIdLenguaje() {
        return this.idLenguaje;
    }
    
    public void setIdLenguaje(Integer idLenguaje) {
        this.idLenguaje = idLenguaje;
    }
    public String getLenguaje() {
        return this.lenguaje;
    }
    
    public void setLenguaje(String lenguaje) {
        this.lenguaje = lenguaje;
    }
    public Set<VideoHasLenguaje> getVideoHasLenguajes() {
        return this.videoHasLenguajes;
    }
    
    public void setVideoHasLenguajes(Set<VideoHasLenguaje> videoHasLenguajes) {
        this.videoHasLenguajes = videoHasLenguajes;
    }




}


