package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private InfoVideo infoVideo;
     private Reparto reparto;
     private String nombrePersona;

    public Persona() {
    }

    public Persona(InfoVideo infoVideo, Reparto reparto, String nombrePersona) {
       this.infoVideo = infoVideo;
       this.reparto = reparto;
       this.nombrePersona = nombrePersona;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public InfoVideo getInfoVideo() {
        return this.infoVideo;
    }
    
    public void setInfoVideo(InfoVideo infoVideo) {
        this.infoVideo = infoVideo;
    }
    public Reparto getReparto() {
        return this.reparto;
    }
    
    public void setReparto(Reparto reparto) {
        this.reparto = reparto;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }




}


