package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RolUsuario generated by hbm2java
 */
public class RolUsuario  implements java.io.Serializable {


     private Integer idRolUsuario;
     private String rolUsuario;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public RolUsuario() {
    }

	
    public RolUsuario(String rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public RolUsuario(String rolUsuario, Set<Usuario> usuarios) {
       this.rolUsuario = rolUsuario;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRolUsuario() {
        return this.idRolUsuario;
    }
    
    public void setIdRolUsuario(Integer idRolUsuario) {
        this.idRolUsuario = idRolUsuario;
    }
    public String getRolUsuario() {
        return this.rolUsuario;
    }
    
    public void setRolUsuario(String rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


