package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1



/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Usuario usuario;
     private String solicitud;

    public Solicitud() {
    }

    public Solicitud(Usuario usuario, String solicitud) {
       this.usuario = usuario;
       this.solicitud = solicitud;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(String solicitud) {
        this.solicitud = solicitud;
    }




}


