package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subtitulo generated by hbm2java
 */
public class Subtitulo  implements java.io.Serializable {


     private Integer idSubtitulo;
     private String subtitulo;
     private Set<VideoHasSubtitulo> videoHasSubtitulos = new HashSet<VideoHasSubtitulo>(0);

    public Subtitulo() {
    }

	
    public Subtitulo(String subtitulo) {
        this.subtitulo = subtitulo;
    }
    public Subtitulo(String subtitulo, Set<VideoHasSubtitulo> videoHasSubtitulos) {
       this.subtitulo = subtitulo;
       this.videoHasSubtitulos = videoHasSubtitulos;
    }
   
    public Integer getIdSubtitulo() {
        return this.idSubtitulo;
    }
    
    public void setIdSubtitulo(Integer idSubtitulo) {
        this.idSubtitulo = idSubtitulo;
    }
    public String getSubtitulo() {
        return this.subtitulo;
    }
    
    public void setSubtitulo(String subtitulo) {
        this.subtitulo = subtitulo;
    }
    public Set<VideoHasSubtitulo> getVideoHasSubtitulos() {
        return this.videoHasSubtitulos;
    }
    
    public void setVideoHasSubtitulos(Set<VideoHasSubtitulo> videoHasSubtitulos) {
        this.videoHasSubtitulos = videoHasSubtitulos;
    }




}


