package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private RolUsuario rolUsuario;
     private String nombre;
     private String correo;
     private String nombreUsuario;
     private String password;
     private String saldo;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Carrito> carritos = new HashSet<Carrito>(0);

    public Usuario() {
    }

	
    public Usuario(RolUsuario rolUsuario, String nombre, String correo, String nombreUsuario, String password, String saldo) {
        this.rolUsuario = rolUsuario;
        this.nombre = nombre;
        this.correo = correo;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.saldo = saldo;
    }
    public Usuario(RolUsuario rolUsuario, String nombre, String correo, String nombreUsuario, String password, String saldo, Set<Solicitud> solicituds, Set<Carrito> carritos) {
       this.rolUsuario = rolUsuario;
       this.nombre = nombre;
       this.correo = correo;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.saldo = saldo;
       this.solicituds = solicituds;
       this.carritos = carritos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public RolUsuario getRolUsuario() {
        return this.rolUsuario;
    }
    
    public void setRolUsuario(RolUsuario rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(String saldo) {
        this.saldo = saldo;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Carrito> getCarritos() {
        return this.carritos;
    }
    
    public void setCarritos(Set<Carrito> carritos) {
        this.carritos = carritos;
    }




}


