package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1



/**
 * VideoHasLenguaje generated by hbm2java
 */
public class VideoHasLenguaje  implements java.io.Serializable {


     private Integer idVideoHasLenguaje;
     private Lenguaje lenguaje;
     private Video video;

    public VideoHasLenguaje() {
    }

    public VideoHasLenguaje(Lenguaje lenguaje, Video video) {
       this.lenguaje = lenguaje;
       this.video = video;
    }
   
    public Integer getIdVideoHasLenguaje() {
        return this.idVideoHasLenguaje;
    }
    
    public void setIdVideoHasLenguaje(Integer idVideoHasLenguaje) {
        this.idVideoHasLenguaje = idVideoHasLenguaje;
    }
    public Lenguaje getLenguaje() {
        return this.lenguaje;
    }
    
    public void setLenguaje(Lenguaje lenguaje) {
        this.lenguaje = lenguaje;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }




}


