package co.edu.uniminuto.arqSw.proyecto.hibernate;
// Generated 29/09/2018 01:38:11 AM by Hibernate Tools 4.3.1



/**
 * VideoHasSubtitulo generated by hbm2java
 */
public class VideoHasSubtitulo  implements java.io.Serializable {


     private Integer idVideoHasSubtitulo;
     private Subtitulo subtitulo;
     private Video video;

    public VideoHasSubtitulo() {
    }

    public VideoHasSubtitulo(Subtitulo subtitulo, Video video) {
       this.subtitulo = subtitulo;
       this.video = video;
    }
   
    public Integer getIdVideoHasSubtitulo() {
        return this.idVideoHasSubtitulo;
    }
    
    public void setIdVideoHasSubtitulo(Integer idVideoHasSubtitulo) {
        this.idVideoHasSubtitulo = idVideoHasSubtitulo;
    }
    public Subtitulo getSubtitulo() {
        return this.subtitulo;
    }
    
    public void setSubtitulo(Subtitulo subtitulo) {
        this.subtitulo = subtitulo;
    }
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }




}


